project:
  name: ucla-dashboard
  owner: team@ucla.edu
  shorten_stack_name: true
  regions:
  - us-west-2
  template: submodules/0-soa.iam.yml
  parameters:
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]

tests:  
  soa-iam:
    parameters: 
      pAppName: soa
      pAppOwner: oscar
      pAppITOwner: Datta
      pCostCenter: IT
      pEnvironment: dev
      pDeploymentMethod: CloudFormation
      pRunType: OnDemand