    QSS3BucketName: tcat-d645d4b80a8b5af09eb075e2cf3e9464-us-west-2
    QSS3BucketRegion: us-west-2
    QSS3KeyPrefix: cloud-formation-soa/
    pAppName: soa
    pAppOwner: Datta
    pAppITOwner: Datta
    pCostCenter: ITSVCS
    pEnvironment: tcatdev
    pDeploymentMethod: CloudFormation
    pRunType: OnDemand
    pVPCID: vpc-0036e64ebfc3da47a
    pPrvStackSubnets: subnet-08363fc81c34a61c7,subnet-01f999dd2c0f6aea5
    pPubStackSubnets: subnet-086743afb9d8e423a,subnet-0c2e4af4069e17b4d
    pVPCCidr: 172.24.7.0/25
    pVPNCidr: 149.142.224.0/23
    pSOAAppSecurityGroup: sg-093f550d09e7b62ef
    pSOADomainName: 607856a5.dev.r53.aws.it.ucla.edu
    pValidationDomain: 607856a5.dev.r53.aws.it.ucla.edu
    pSOAStorageEncrypted: "true"
    pSOAAppStorageEncrypted: "true"
    pSOADBEngine: aurora-mysql
    pSOADBEngineVersion: 5.7.mysql_aurora.2.09.0
    pSOADBInstanceType: db.r5.large
    pSOADBBackupRetention: 35
    pDBMultiAZ: "true"
    pSOADBBackupWindow: 3:00-4:00
    pSOADBMaintenanceWindow: sun:5:00-sun:6:00
    pMQInstanceType: mq.m5.large
    pMQMultiAZ: "true"
    pLoadBalancerScheme: internet-facing
    pSOAAppKeyPairName: soa-dashboard-ec2-keypair
    pBaseAMI: ami-0528a5175983e7f28
    pSOAAppASGMin: 1
    pSOAAppASGMax: 1
