AWSTemplateFormatVersion: "2010-09-09"
Description: Deploys the UCLA Dashboard app and related resources.
Metadata:
  QuickStartDocumentation:
    EntrypointName: "Launch Infrastructure for the Dashboard App"
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Basic configuration
        Parameters:
          - pAppName
          - pAppOwner
          - pAppITOwner
          - pCostCenter
          - pEnvironment
          - pDeploymentMethod
          - pRunType
      - Label:
          default: Core Configuration
        Parameters:
          - pVPCID
          - pPrvStackSubnets
          - pPubStackSubnets
          - pVPCCidr
          - pSOAAppSecurityGroup
          - pVPNCidr
          - pSOADomainName
          - pValidationDomain
          - pSOAStorageEncrypted
          - pSOADBEngine
          - pSOADBEngineVersion
          - pSOADBInstanceType
          - pDBMultiAZ
          - pSOADBBackupRetention
          - pSOADBBackupWindow
          - pSOADBMaintenanceWindow
          - pMQInstanceType
          - pMQMultiAZ

      - Label:
          default: App Configuration
        Parameters:
          - pLoadBalancerScheme
          - pSOAAppStorageEncrypted
          - pSOAAppInstanceType
          - pSOAAppKeyPairName
          - pBaseAMI
          - pSOAAppASGMin
          - pSOAAppASGMax

      - Label:
          default: AWS Template configuration S3 Bucket Location
        Parameters:
          - QSS3BucketName
          - QSS3KeyPrefix
          - QSS3BucketRegion

    ParameterLabels:
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix
      QSS3BucketRegion:
        default: Quick Start S3 bucket Region
      pAppName: 
        default: The app name
      pAppOwner:
        default: The name of the app owner
      pAppITOwner: 
        default: The name or alias of the IT Owner
      pCostCenter: 
        default: The Cost Center this workload should be charged to
      pEnvironment: 
        default: What environment will this be deployed to?
      pDeploymentMethod: 
        default: What method will this be deployed with?
      pRunType: 
        default: What runtime is being used?
      pVPCID:
        default: VPC
      pPrvStackSubnets:
        default: A comma delimited list of private subnets.
      pPubStackSubnets:
        default: Public Subnets to deploy the load balancer
      pVPCCidr:
        default: VPC CIDR
      pSOAAppSecurityGroup:
        default: Security Group
      pVPNCidr:
        default: VPN CIDR
      pSOADomainName:
        default: A domain i.e. ucla.edu
      pValidationDomain:
        default: A validation domain i.e. ucla.edu
      pSOAStorageEncrypted:
        default: Encrypt Storage
      pSOADBEngine:
        default: The Engine
      pSOADBEngineVersion:
        default: The Engine version being used
      pSOADBInstanceType:
        default: The Instance Type
      pDBMultiAZ:
        default: If deploying in multiple Availability Zones
      pSOADBBackupRetention:
        default: The data retention period.
      pSOADBBackupWindow:
        default: The backup window desired.
      pSOADBMaintenanceWindow:
        default: The maintenance window
      pMQInstanceType:
        default: The MQ instance type
      pMQMultiAZ:
        default: The MQ is deployed to multiple Availability Zones
      pLoadBalancerScheme:
        default: Load balancer visibility
      # pSOAAppCert:
      #   default: SOAApp certificate ARN
      # pSOAAppKMSID:
      #   default: KMS CMK Key id for encryption
      pSOAAppInstanceType:
        default: SOAApp ec2 instance type
      pSOAAppKeyPairName:
        default: EC2 instance login key pair name
      pBaseAMI:
        default: AMI Id of SOAApp app instance
      pSOAAppASGMin:
        default:  Min nbr of instances to be launched with auto scaling group
      pSOAAppASGMax:
        default: Max nbr of instances to be launched with auto scaling group  
      

Parameters:
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: 'Solution bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).'
    Default: aws-quickstart
    Description: 'S3 bucket name for the Quick Start assets. This string can include
      numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start
      or end with a hyphen (-).'
    Type: String
  QSS3KeyPrefix:
      AllowedPattern: ^[0-9a-zA-Z-/.]*$
      ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters,
        uppercase letters, hyphens (-), periods (.) and forward slash (/).
      Default: cloud-formation-soa/
      Description: S3 key prefix for the Quick Start assets. Quick Start key prefix
        can include numbers, lowercase letters, uppercase letters, hyphens (-), periods (.) and
        forward slash (/).
      Type: String
  QSS3BucketRegion:
    Default: 'us-east-1'
    Description: Region where the Quick Start S3 bucket (QSS3BucketName) is
      hosted. When using your own bucket, you must specify this value.
    Type: String

  pAppName:
    Type: String 
    Description: Application name
    Default: 'soa'

  pAppOwner:
    Type: String 
    Description: Application Business Owner
    Default: 'Oscar'

  pAppITOwner:
    Type: String 
    Description: Application IT Owner
    Default: 'Datta'

  pCostCenter:
    Type: String 
    Description: Cost Center
    Default: '48484'

  pEnvironment:
    Type: String 
    Description: Environment
    Default: dev
    AllowedValues:
      - prod
      - test
      - dev
  pDeploymentMethod:
    Type: String 
    Description: Deployment Tool name
    Default: CloudFormation
  pRunType:
    Type: String 
    Description: KMS CMK Key id for encryption
    Default: Scheduled
    AllowedValues:
      - OnDemand
      - AutoScaling
      - Scheduled
  pVPCID:
    Description: VPC id for deployment of this stack.
    Type: String
    Default: vpc-bd0344c5
  pPrvStackSubnets:
    Description: Private Subnets to deploy the app servers
    Type: String
    Default: subnet-172bfa6f,subnet-efdf2da5
  pPubStackSubnets:
      Description: Public Subnets to deploy the load balancer
      Type: String
      Default: subnet-75b3e85e,subnet-52df7c0f
  pLoadBalancerScheme:
    Description: Load balancer visibility
    Type: String
    AllowedValues:
     - internal
     - internet-facing
  pSOAAppKeyPairName:
    Description: EC2 instance login key pair name
    Type: AWS::EC2::KeyPair::KeyName
  pVPCCidr:
    Description: VPC cidr
    Type: String
    Default: 172.31.32.0/20
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
  pVPNCidr:
    Description: VPN cidr
    Type: String
    Default: 172.31.32.0/20
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
  pSOAAppSecurityGroup:
    Description: SOA app ec2 instance security group
    Type: String
    Default: sg-ab9e9983
  pSOADomainName:
    Description: soa domain name
    Type: String
    Default: clusters.sharepointoscar.com
  pValidationDomain:
    Description: Validation domain name
    Type: String
    Default: clusters.sharepointoscar.com
  pSOAStorageEncrypted:
    Type: String
    Description: Encrypt db storage
    Default: true
    AllowedValues:
      - true
      - false
  pSOADBEngine:
    Type: String
    Description: Database Engine
    Default: aurora-mysql
  pSOADBEngineVersion:
    Type: String
    Description: Database version
    Default: 5.7.mysql_aurora.2.09.0
  pSOADBInstanceType:
    Type: String
    Description: DB instance type
    Default: db.r5.large
  pSOADBBackupRetention:
    Type: String
    Description: DB backup retention in days 0 - 35
    Default: 35
  pDBMultiAZ:
    Type: String
    Description: High availability/Multi AZ deployement
    Default: true
    AllowedValues:
      - true
      - false
  pSOADBBackupWindow:
    Type: String
    Description: Backup window in UTC format hh24:mi-hh24:mi should not be same as Maintenance Window
    Default: 3:00-4:00
  pSOADBMaintenanceWindow:
    Type: String
    Description: Maintenance window in UTC format ddd:hh24:mi-ddd:hh24:mi should not be same as Backup Window
    Default: sun:5:00-sun:6:00
  pMQInstanceType:
    Type: String
    Description: MQ broker ec2 instance type
    Default: mq.t2.micro
    AllowedValues:
      - mq.t2.micro
      - mq.m5.large
      - mq.m5.xlarge
  pMQMultiAZ:
    Type: String
    Description: Deploy in HA configuration
    Default: true
    AllowedValues:
        - true
        - false
  pBaseAMI:
    Description: AMI Id of SOAApp app instance
    Type: String
    Default: ami-0518bb0e75d3619ca
  pSOAAppASGMin:
    Description: Min nbr of instances to be launched with auto scaling group
    Type: String
    Default: 1
  pSOAAppASGMax:
    Description: Max nbr of instances to be launched with auto scaling group
    Type: String
    Default: 2
  pSOAAppStorageEncrypted:
    Type: String
    Description: Encrypt db & efs storage
    Default: "true"
    AllowedValues:
      - True
      - False
  pSOAAppInstanceType:
    Type: String
    Description: SOAApp ec2 instance type
    Default: t2.small
    AllowedValues:
      - t2.small
      - m5.large
      - m5.xlarge
Conditions:
  UsingDefaultBucket: !Equals [!Ref QSS3BucketName, 'aws-quickstart']
Resources:
  IAMStack:
    Type: AWS::CloudFormation::Stack
    Metadata: { cfn-lint: { config: { ignore_checks: [E9902, W9901] } } }
    Properties:
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/0-soa-iam.yml'
        - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        pAppName: !Ref pAppName
        pAppOwner: !Ref pAppOwner
        pAppITOwner: !Ref pAppITOwner
        pCostCenter: !Ref pCostCenter
        pEnvironment: !Ref pEnvironment
        pDeploymentMethod: !Ref pDeploymentMethod
        pRunType: !Ref pRunType

  MQStack:
    Type: AWS::CloudFormation::Stack
    Metadata: { cfn-lint: { config: { ignore_checks: [E9902, W9901] } } }
    DependsOn: 
      - IAMStack
    Properties:
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/1-soa-mqconf.yml'
        - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        pAppName: !Ref pAppName
        pAppOwner: !Ref pAppOwner
        pAppITOwner: !Ref pAppITOwner
        pCostCenter: !Ref pCostCenter
        pEnvironment: !Ref pEnvironment
        pDeploymentMethod: !Ref pDeploymentMethod
        pRunType: !Ref pRunType
  CoreStack:
      Type: AWS::CloudFormation::Stack
      Metadata: 
        cfn-lint: { config: { ignore_checks: [ W9901 ] } }
      DependsOn: 
        - IAMStack
        - MQStack
      Properties:
        TemplateURL: !Sub
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/2-soa-core.yml'
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
        Parameters:
          pAppName: !Ref pAppName
          pAppOwner: !Ref pAppOwner
          pAppITOwner: !Ref pAppITOwner
          pCostCenter: !Ref pCostCenter
          pEnvironment: !Ref pEnvironment
          pDeploymentMethod: !Ref pDeploymentMethod
          pRunType: !Ref pRunType
          pVPCID: !Ref pVPCID
          pPrvStackSubnets: !Ref pPrvStackSubnets
          pVPCCidr: !Ref pVPCCidr
          pSOAAppSecurityGroup: !Ref pSOAAppSecurityGroup
          pVPNCidr: !Ref pVPNCidr
          pSOADomainName: !Ref pSOADomainName
          pValidationDomain: !Ref pValidationDomain
          pSOAStorageEncrypted: !Ref pSOAStorageEncrypted
          pSOADBEngine: !Ref pSOADBEngine
          pSOADBEngineVersion: !Ref pSOADBEngineVersion
          pSOADBInstanceType: !Ref pSOADBInstanceType
          pDBMultiAZ: !Ref pDBMultiAZ
          pSOADBBackupRetention: !Ref pSOADBBackupRetention
          pSOADBBackupWindow: !Ref pSOADBBackupWindow
          pSOADBMaintenanceWindow: !Ref pSOADBMaintenanceWindow
          pMQInstanceType: !Ref pMQInstanceType
          pMQMultiAZ: !Ref pMQMultiAZ
          pMQConfigId: !GetAtt MQStack.Outputs.oMQConfigurationId
          pMQConfigRevision: !GetAtt MQStack.Outputs.oMQConfigurationRevisionNbr
          pEc2RoleName: !GetAtt IAMStack.Outputs.oSSMRoleName

  AppStack:
    Type: AWS::CloudFormation::Stack
    Metadata: 
      cfn-lint: { config: { ignore_checks: [ W9901 ] } }
    DependsOn: 
      - CoreStack
    Properties:
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/3-soa-app.yml'
        - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        pAppName: !Ref pAppName
        pAppOwner: !Ref pAppOwner
        pAppITOwner: !Ref pAppITOwner
        pCostCenter: !Ref pCostCenter
        pEnvironment: !Ref pEnvironment
        pDeploymentMethod: !Ref pDeploymentMethod
        pRunType: !Ref pRunType
        pVPCID: !Ref pVPCID
        pVPCCidr: !Ref pVPCCidr
        pPrvStackSubnets: !Ref pPrvStackSubnets
        pPubStackSubnets: !Ref pPubStackSubnets
        pLoadBalancerScheme: !Ref pLoadBalancerScheme 
        pSOAAppCert: !GetAtt CoreStack.Outputs.osoaCertificate
        pSOAAppStorageEncrypted: !Ref pSOAAppStorageEncrypted
        pSOAAppKMSID: !GetAtt CoreStack.Outputs.oKmsCmk
        pSOAAppInstanceType: !Ref pSOAAppInstanceType
        pSOAAppKeyPairName: !Ref pSOAAppKeyPairName
        pBaseAMI: !Ref pBaseAMI
        pSOAAppASGMin: !Ref pSOAAppASGMin
        pSOAAppASGMax: !Ref pSOAAppASGMax
        pAutoScalingServiceRoleARN: !GetAtt IAMStack.Outputs.oAutoScalingARN